# joint_state_controller:
#   type: joint_state_controller/JointStateController
#   publish_rate: 50.0
# bh_j11_position_controller:
#   type: position_controllers/JointPositionController
#   joint: bh_j11_joint
# bh_j12_position_controller:
#   type: position_controllers/JointPositionController
#   joint: bh_j12_joint
# bh_j22_position_controller:
#   type: position_controllers/JointPositionController
#   joint: bh_j22_joint
# bh_j32_position_controller:
#   type: position_controllers/JointPositionController
#   joint: bh_j32_joint

gripper_controller:
   # type: gripper_action/GripperCommand
   type: position_controllers/JointTrajectoryController
   joints:
      - bh_j11_joint
      - bh_j12_joint
      - bh_j13_joint
      - bh_j21_joint
      - bh_j22_joint
      - bh_j23_joint
      - bh_j32_joint
      - bh_j33_joint
