# joint_state_controller:
#   type: joint_state_controller/JointStateController
#   publish_rate: 50.0 
# bh_j11_position_controller:
#   type: position_controllers/JointPositionController
#   joint: bh_j11_joint
# bh_j12_position_controller:
#   type: position_controllers/JointPositionController
#   joint: bh_j12_joint
# bh_j13_position_controller:
#   type: position_controllers/JointPositionController
#   joint: bh_j13_joint
# bh_j21_position_controller:
#   type: position_controllers/JointPositionController
#   joint: bh_j21_joint
# bh_j22_position_controller:
#   type: position_controllers/JointPositionController
#   joint: bh_j22_joint
# bh_j23_position_controller:
#   type: position_controllers/JointPositionController
#   joint: bh_j23_joint
# bh_j32_position_controller:
#   type: position_controllers/JointPositionController
#   joint: bh_j32_joint
# bh_j33_position_controller:
#   type: position_controllers/JointPositionController
#   joint: bh_j33_joint

gripper_controller:
   # type: gripper_action/GripperCommand
   type: position_controllers/JointTrajectoryController
   # type: effort_controllers/JointTrajectoryController
   joints:
      - bh_j11_joint
      - bh_j12_joint
      - bh_j13_joint
      - bh_j21_joint
      - bh_j22_joint
      - bh_j23_joint
      - bh_j32_joint
      - bh_j33_joint
   # Uncomment gains in case, effort_controllers are used
   # gains: # Required because we're controlling an effort interface
   #    bh_j11_joint: {p: 100,  d: 1, i: 1, i_clamp: 1}
   #    bh_j12_joint: {p: 100,  d: 1, i: 1, i_clamp: 1}
   #    bh_j13_joint: {p: 100,  d: 1, i: 1, i_clamp: 1} 
   #    bh_j21_joint: {p: 100,  d: 1, i: 1, i_clamp: 1}
   #    bh_j22_joint: {p: 100,  d: 1, i: 1, i_clamp: 1}
   #    bh_j23_joint: {p: 100,  d: 1, i: 1, i_clamp: 1}
   #    bh_j32_joint: {p: 100,  d: 1, i: 1, i_clamp: 1}
   #    bh_j33_joint: {p: 100,  d: 1, i: 1, i_clamp: 1}
