joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 1000

computed_torque_controller:
  type: kuka_barrett_control/ComputedTorqueControllerTest
  joints:
    - iiwa_joint_1
    - iiwa_joint_2
    - iiwa_joint_3
    - iiwa_joint_4
    - iiwa_joint_5
    - iiwa_joint_6
    - iiwa_joint_7
  gains:
    # iiwa_joint_1: 
    #   pid: {p: 100.0, i: 0, d: 20.0}
    # iiwa_joint_2: 
    #   pid: {p: 100.0, i: 0, d: 20.0}
    # iiwa_joint_3: 
    #   pid: {p: 100.0, i: 0, d: 20.0}
    # iiwa_joint_4: 
    #   pid: {p: 100.0, i: 0, d: 20.0}
    # iiwa_joint_5: 
    #   pid: {p: 100.0, i: 0, d: 20.0}
    # iiwa_joint_6: 
    #   pid: {p: 100.0, i: 0, d: 20.0}
    # iiwa_joint_7: 
    #   pid: {p: 100.0, i: 0, d: 20.0}
    iiwa_joint_1: 
      pid: {p: 400.0, i: 200, d: 20.0}
    iiwa_joint_2: 
      pid: {p: 100.0, i: 100, d: 20.0}
    iiwa_joint_3: 
      pid: {p: 400.0, i: 100, d: 20.0}
    iiwa_joint_4: 
      pid: {p: 100.0, i: 0, d: 20.0}
    iiwa_joint_5: 
      pid: {p: 100.0, i: 0, d: 20.0}
    iiwa_joint_6: 
      pid: {p: 100.0, i: 0, d: 20.0}
    iiwa_joint_7: 
      pid: {p: 100.0, i: 0, d: 20.0}
  root_link: world
  tip_link: iiwa_link_7


gripper_controller:
  # type: gripper_action/GripperCommand
  type: position_controllers/JointTrajectoryController
  joints:
    - bh_j11_joint
    - bh_j12_joint
    - bh_j13_joint
    - bh_j21_joint
    - bh_j22_joint
    - bh_j23_joint
    - bh_j32_joint
    - bh_j33_joint
      