controller_list:
  - name: arm_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints: 
      - iiwa_joint_1
      - iiwa_joint_2
      - iiwa_joint_3
      - iiwa_joint_4
      - iiwa_joint_5
      - iiwa_joint_6
      - iiwa_joint_7
  - name: gripper_controller
    # action_ns: gripper_action
    # type: GripperCommand
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - bh_j11_joint
      - bh_j12_joint
      - bh_j13_joint
      - bh_j21_joint
      - bh_j22_joint
      - bh_j23_joint
      - bh_j32_joint
      - bh_j33_joint