# MoveIt-specific simulation settings
moveit_sim_hw_interface:
  joint_model_group: controllers_initial_group_
  joint_model_group_pose: controllers_initial_pose_
# Settings for ros_control control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - iiwa_joint_1
    - iiwa_joint_2
    - iiwa_joint_3
    - iiwa_joint_4
    - iiwa_joint_5
    - iiwa_joint_6
    - iiwa_joint_7
    - bh_j11_joint
    - bh_j12_joint
    - bh_j13_joint
    - bh_j21_joint
    - bh_j22_joint
    - bh_j23_joint
    - bh_j32_joint
    - bh_j33_joint
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
controller_list:
  - name: arm_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - iiwa_joint_1
      - iiwa_joint_2
      - iiwa_joint_3
      - iiwa_joint_4
      - iiwa_joint_5
      - iiwa_joint_6
      - iiwa_joint_7
arm_position_controller:
  type: effort_controllers/JointPositionController
  joints:
    - iiwa_joint_1
    - iiwa_joint_2
    - iiwa_joint_3
    - iiwa_joint_4
    - iiwa_joint_5
    - iiwa_joint_6
    - iiwa_joint_7
  gains:
    iiwa_joint_1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    iiwa_joint_2:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    iiwa_joint_3:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    iiwa_joint_4:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    iiwa_joint_5:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    iiwa_joint_6:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    iiwa_joint_7:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
arm_effort_controller:
  type: effort_controllers/JointEffortController
  joints:
    - iiwa_joint_1
    - iiwa_joint_2
    - iiwa_joint_3
    - iiwa_joint_4
    - iiwa_joint_5
    - iiwa_joint_6
    - iiwa_joint_7
  gains:
    iiwa_joint_1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    iiwa_joint_2:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    iiwa_joint_3:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    iiwa_joint_4:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    iiwa_joint_5:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    iiwa_joint_6:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    iiwa_joint_7:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
gripper_effort_controller:
  type: effort_controllers/JointEffortController
  joints:
    - bh_j11_joint
    - bh_j12_joint
    - bh_j13_joint
    - bh_j21_joint
    - bh_j22_joint
    - bh_j23_joint
    - bh_j32_joint
    - bh_j33_joint
  gains:
    bh_j11_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    bh_j12_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    bh_j13_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    bh_j21_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    bh_j22_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    bh_j23_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    bh_j32_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    bh_j33_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1